extensions:
    snowio-csv-export-edit:
        module: pim/form/common/edit-form

    snowio-csv-export-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: snowio-csv-export-edit
        position: 1000

    snowio-csv-export-edit-tabs:
        module: pim/form/common/form-tabs
        parent: snowio-csv-export-edit
        targetZone: content
        position: 100

    snowio-csv-export-edit-properties:
        module: pim/job/common/edit/properties
        parent: snowio-csv-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    snowio-csv-export-edit-history:
        module: pim/common/tab/history
        parent: snowio-csv-export-edit-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: pim-job-instance-history

    snowio-csv-export-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-export-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    snowio-csv-export-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-export-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: false

    snowio-csv-export-edit-properties-delimiter:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-export-edit-properties
        position: 120
        targetZone: global-settings
        config:
            fieldCode: configuration.delimiter
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_enrich.form.job_instance.tab.properties.delimiter.help

    snowio-csv-export-edit-properties-enclosure:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-export-edit-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.enclosure
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_enrich.form.job_instance.tab.properties.enclosure.help

    snowio-csv-export-edit-properties-with-header:
        module: pim/job/common/edit/field/switch
        parent: snowio-csv-export-edit-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.withHeader
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.with_header.title
            tooltip: pim_enrich.form.job_instance.tab.properties.with_header.help

    snowio-csv-export-edit-properties-endpoint:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-export-edit-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.endpoint
            readOnly: false
            label: snowio_connector.form.job_instance.tab.properties.endpoint.title
            tooltip: snowio_connector.form.job_instance.tab.properties.endpoint.help

    snowio-csv-export-edit-properties-application-id:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-export-edit-properties
        position: 160
        targetZone: global-settings
        config:
            fieldCode: configuration.applicationId
            readOnly: false
            label: snowio_connector.form.job_instance.tab.properties.application_id.title
            tooltip: snowio_connector.form.job_instance.tab.properties.application_id.help

    snowio-csv-export-edit-properties-secret-key:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-export-edit-properties
        position: 170
        targetZone: global-settings
        config:
            fieldCode: configuration.secretKey
            readOnly: false
            label: snowio_connector.form.job_instance.tab.properties.secret_key.title
            tooltip: snowio_connector.form.job_instance.tab.properties.secret_key.help

    snowio-csv-export-edit-properties-export-dir:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-export-edit-properties
        position: 180
        targetZone: global-settings
        config:
            fieldCode: configuration.exportDir
            readOnly: false
            label: snowio_connector.form.job_instance.tab.properties.export_dir.title
            tooltip: snowio_connector.form.job_instance.tab.properties.export_dir.help

    snowio-csv-export-edit-properties-rsync-directory:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-export-edit-properties
        position: 190
        targetZone: global-settings
        config:
            fieldCode: configuration.rsyncDirectory
            readOnly: false
            label: snowio_connector.form.job_instance.tab.properties.rsync_directory.title
            tooltip: snowio_connector.form.job_instance.tab.properties.rsync_directory.help

    snowio-csv-export-edit-properties-rsync-user:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-export-edit-properties
        position: 200
        targetZone: global-settings
        config:
            fieldCode: configuration.rsyncUser
            readOnly: false
            label: snowio_connector.form.job_instance.tab.properties.rsync_user.title
            tooltip: snowio_connector.form.job_instance.tab.properties.rsync_user.help

    snowio-csv-export-edit-properties-rsync-host:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-export-edit-properties
        position: 210
        targetZone: global-settings
        config:
            fieldCode: configuration.rsyncHost
            readOnly: false
            label: snowio_connector.form.job_instance.tab.properties.rsync_host.title
            tooltip: snowio_connector.form.job_instance.tab.properties.rsync_host.help

    snowio-csv-export-edit-properties-rsync-options:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-export-edit-properties
        position: 200
        targetZone: global-settings
        config:
            fieldCode: configuration.rsyncOptions
            readOnly: false
            label: snowio_connector.form.job_instance.tab.properties.rsync_options.title
            tooltip: snowio_connector.form.job_instance.tab.properties.rsync_options.help

    snowio-csv-export-edit-label:
        module: pim/job/common/edit/label
        parent: snowio-csv-export-edit
        targetZone: title
        position: 100

    snowio-csv-export-edit-meta:
        module: pim/job/common/edit/meta
        parent: snowio-csv-export-edit
        targetZone: meta
        position: 100

    snowio-csv-export-edit-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: snowio-csv-export-edit
        targetZone: back
        aclResourceId: pim_importexport_export_profile_index
        position: 80
        config:
            backUrl: pim_importexport_export_profile_index

    snowio-csv-export-edit-delete:
        module: pim/job/export/edit/delete
        parent: snowio-csv-export-edit
        targetZone: buttons
        aclResourceId: pim_importexport_export_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.job_instance
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_export_profile_index

    snowio-csv-export-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: snowio-csv-export-edit
        targetZone: buttons
        position: 120

    snowio-csv-export-edit-save:
        module: pim/job-instance-export-edit-form/save
        parent: snowio-csv-export-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_export_profile_show

    snowio-csv-export-edit-state:
        module: pim/form/common/state
        parent: snowio-csv-export-edit
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.job_instance.title

    snowio-csv-export-edit-validation:
        module: pim/job/common/edit/validation
        parent: snowio-csv-export-edit
